package com.billing.dsl.constant

enum class ResponseCode {

    BILLING_UNAVAILABLE,
    DEVELOPER_ERROR,
    ERROR,
    FEATURE_NOT_SUPPORTED,
    ITEM_ALREADY_OWNED,
    ITEM_NOT_OWNED,
    ITEM_UNAVAILABLE,
    OK,
    SERVICE_DISCONNECTED,
    SERVICE_TIMEOUT,
    SERVICE_UNAVAILABLE,
    USER_CANCELED,
    UNDEFINED
}